services:
  postgres:
    image: postgres:16-alpine
    container_name: hossein-hub-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - postgres_password
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks: [hub-backend]
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 10
  archive-api:
    build: ./app/backend
    container_name: hossein-hub-archive
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      ARCHIVE_ROOT: /archive
    secrets:
      - postgres_password
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./archive:/archive
    ports:
      - "192.168.1.35:8080:8080"
    networks: [hub-backend]
secrets:
  postgres_password:
    file: ./secrets/postgres_password
networks:
  hub-backend:
    external: true
    name: hossein-hub-backend
