// Executive-assistant workspace. All inferred actions stay pending until Hossein confirms.
(()=>{
 const byId=id=>document.getElementById(id);
 const safe=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
 const get=async path=>{const r=await fetch('/api/personal/v2/'+path);const d=await r.json();if(!r.ok)throw Error(d.detail||'عملیات ناموفق بود');return d};
 const send=async(path,data,method='POST')=>{const r=await fetch('/api/personal/v2/'+path,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(data||{})});const d=await r.json();if(!r.ok)throw Error(d.detail||'عملیات ناموفق بود');return d};
 const fmt=value=>{if(!value)return '';const d=new Date(value);return isNaN(d)?String(value).slice(0,16):new Intl.DateTimeFormat('fa-IR',{dateStyle:'medium',timeStyle:value.includes('T')?'short':undefined}).format(d)};
 const emptyText=text=>`<div class="assistant-empty">${safe(text)}</div>`;

 const css=document.createElement('style');css.textContent=`
 .assistant-sheet{max-height:96vh}.assistant-tabs{display:flex;gap:7px;overflow:auto;padding:1px 0 13px;scrollbar-width:none}.assistant-tab{white-space:nowrap;border:1px solid #e3e6ef;background:#fff;color:#70788d;border-radius:12px;padding:8px 11px;font:inherit;font-size:10px}.assistant-tab.active{background:#182033;color:#fff;border-color:#182033}.assistant-panel{display:none}.assistant-panel.active{display:block}.assistant-card{background:#fff;border:1px solid #e5e8f0;border-radius:17px;padding:13px;margin-bottom:9px}.assistant-card h3{font-size:13px;margin:0 0 5px;line-height:1.8}.assistant-card p{font-size:11px;color:#737c91;line-height:1.9;margin:0;white-space:pre-wrap}.assistant-meta{display:flex;gap:6px;flex-wrap:wrap;margin-top:9px}.assistant-tag{font-size:9px;padding:4px 7px;border-radius:8px;background:#eef0ff;color:#5266db}.assistant-tag.high{background:#fff0ed;color:#d95448}.assistant-tag.medium{background:#fff5df;color:#ad741b}.assistant-buttons{display:flex;gap:7px;flex-wrap:wrap;margin-top:10px}.assistant-buttons button,.assistant-button{border:0;border-radius:10px;padding:8px 10px;background:#eef0ff;color:#5266db;font:inherit;font-size:10px;text-decoration:none}.assistant-buttons .accept{background:#e8f8f2;color:#188c69}.assistant-buttons .reject{background:#f2f3f7;color:#747c91}.assistant-metrics{display:grid;grid-template-columns:repeat(2,1fr);gap:8px;margin-bottom:12px}.assistant-metric{background:#fff;border:1px solid #e6e8f0;border-radius:15px;padding:12px}.assistant-metric b{display:block;font-size:20px;color:#5b6ff7}.assistant-metric span{font-size:9px;color:#778095}.assistant-empty{padding:24px;text-align:center;color:#8990a2;border:1px dashed #dfe2eb;border-radius:16px}.assistant-search{display:flex;gap:7px;margin-bottom:12px}.assistant-search input,.assistant-review textarea{flex:1;border:1px solid #dfe2eb;background:#fff;border-radius:13px;padding:11px;font:inherit;font-size:12px}.assistant-search button{border:0;border-radius:12px;background:#5b6ff7;color:#fff;padding:0 14px}.assistant-source{border-right:3px solid #8d5cf6}.assistant-review textarea{width:100%;min-height:100px;resize:vertical}.assistant-section-title{display:flex;justify-content:space-between;align-items:center;margin:5px 2px 10px}.assistant-section-title h3{margin:0;font-size:14px}.assistant-section-title button{border:0;background:#eef0ff;color:#5266db;border-radius:10px;padding:7px 9px;font:inherit;font-size:9px}
 `;document.head.append(css);

 const shell=document.createElement('div');shell.innerHTML=`
 <div class="sheet-wrap" id="assistantSheet"><div class="sheet assistant-sheet"><div class="handle"></div><div class="sheet-head"><h2>مرکز هوشمند همراه من</h2><button class="close" id="assistantClose">×</button></div>
 <div class="assistant-tabs" id="assistantTabs">
  <button class="assistant-tab active" data-panel="brief">امروز</button><button class="assistant-tab" data-panel="suggestions">پیشنهادها</button><button class="assistant-tab" data-panel="risks">رادار خطر</button><button class="assistant-tab" data-panel="memory">حافظه</button><button class="assistant-tab" data-panel="commitments">تعهدها</button><button class="assistant-tab" data-panel="decisions">تصمیم‌ها</button><button class="assistant-tab" data-panel="calendar">تقویم</button><button class="assistant-tab" data-panel="people">افراد</button><button class="assistant-tab" data-panel="timeline">خط زمانی</button><button class="assistant-tab" data-panel="review">مرور روز</button>
 </div>
 <section class="assistant-panel active" id="assistant-brief"><div id="assistantBrief"></div></section>
 <section class="assistant-panel" id="assistant-suggestions"><div id="assistantSuggestions"></div></section>
 <section class="assistant-panel" id="assistant-risks"><div id="assistantRisks"></div></section>
 <section class="assistant-panel" id="assistant-memory"><div class="assistant-search"><input id="memoryQuery" placeholder="از حافظه‌ام بپرس…"><button id="memoryAsk">بپرس</button></div><div id="memoryResults"></div></section>
 <section class="assistant-panel" id="assistant-commitments"><div class="assistant-section-title"><h3>قول‌ها و موضوعات منتظر</h3><button id="newCommitment">+ تعهد</button></div><div id="assistantCommitments"></div></section>
 <section class="assistant-panel" id="assistant-decisions"><div class="assistant-section-title"><h3>دفتر تصمیم‌ها</h3><button id="newDecision">+ تصمیم</button></div><div id="assistantDecisions"></div></section>
 <section class="assistant-panel" id="assistant-calendar"><div class="assistant-section-title"><h3>موعدها و رویدادها</h3><div class="assistant-buttons"><button id="syncCalendar">همگام‌سازی</button><button id="calendarConfig">تنظیم ICS</button><button id="newEvent">+ رویداد</button></div></div><div id="assistantCalendar"></div></section>
 <section class="assistant-panel" id="assistant-people"><div id="assistantPeople"></div></section>
 <section class="assistant-panel" id="assistant-timeline"><div id="assistantTimeline"></div></section>
 <section class="assistant-panel" id="assistant-review"><div class="assistant-card assistant-review"><h3>مرور صبح</h3><textarea id="morningReview" placeholder="سه اولویت اصلی، محدودیت امروز و اولین اقدام…"></textarea><div class="assistant-buttons"><button class="accept" data-review="morning">ذخیره مرور صبح</button></div></div><div class="assistant-card assistant-review"><h3>مرور شب</h3><textarea id="eveningReview" placeholder="چه چیزی انجام شد، چه چیزی منتقل شود و چه حلقه‌ای باز ماند؟"></textarea><div class="assistant-buttons"><button class="accept" data-review="evening">ذخیره مرور شب</button></div></div><div class="assistant-buttons"><a class="assistant-button" href="/api/personal/v2/export">دریافت خروجی کامل JSON</a></div></section>
 </div></div>`;document.body.append(shell);

 const actionBar=document.querySelector('#todayView .connect-actions');
 if(actionBar){const button=document.createElement('button');button.id='assistantOpen';button.textContent='✦ دستیار هوشمند';actionBar.prepend(button)}

 const card=(title,detail,tags='',buttons='')=>`<article class="assistant-card"><h3>${safe(title)}</h3>${detail?`<p>${safe(detail)}</p>`:''}<div class="assistant-meta">${tags}</div>${buttons?`<div class="assistant-buttons">${buttons}</div>`:''}</article>`;
 const tag=(text,klass='')=>`<span class="assistant-tag ${klass}">${safe(text)}</span>`;

 async function loadBrief(){const d=await get('brief');byId('assistantBrief').innerHTML=`<div class="assistant-card"><h3>${safe(d.message)}</h3><p>این گزارش فقط از اطلاعات ثبت‌شده ساخته شده است.</p></div><div class="assistant-metrics"><div class="assistant-metric"><b>${fa(d.counts.pending_suggestions)}</b><span>پیشنهاد منتظر تأیید</span></div><div class="assistant-metric"><b>${fa(d.counts.waiting_commitments)}</b><span>تعهد منتظر</span></div><div class="assistant-metric"><b>${fa(d.counts.email_captures)}</b><span>ایمیل بررسی‌نشده</span></div><div class="assistant-metric"><b>${fa(d.counts.risks)}</b><span>موضوع نیازمند توجه</span></div></div><div class="assistant-section-title"><h3>سه تمرکز اصلی</h3></div>${d.focus.length?d.focus.map(x=>card(x.title,x.due_at?'موعد: '+fmt(x.due_at):'',tag(x.status))).join(''):emptyText('هنوز اولویتی برای امروز مشخص نشده است')}<div class="assistant-section-title"><h3>هشدارهای مهم</h3></div>${d.risks.length?d.risks.map(x=>card(x.title,x.detail,tag(x.level,x.level))).join(''):emptyText('هشدار فعالی وجود ندارد')}`}
 async function loadSuggestions(){const d=await get('suggestions');byId('assistantSuggestions').innerHTML=d.items.length?d.items.map(x=>card(x.title,x.raw_text,tag(({task:'کار',note:'یادداشت',fact:'Fact',commitment:'تعهد',decision:'تصمیم',event:'رویداد',person:'شخص'}[x.kind]||x.kind)+' · '+fa(x.confidence)+'٪'),`<button class="accept" onclick="assistantDecision('${x.id}','accept')">تأیید</button><button class="reject" onclick="assistantDecision('${x.id}','reject')">رد</button>`)).join(''):emptyText('پیشنهاد منتظر تأییدی وجود ندارد')}
 window.assistantDecision=async(id,action)=>{try{await send('suggestions/'+id+'/decide',{action});toast(action==='accept'?'پیشنهاد تأیید و ثبت شد':'پیشنهاد رد شد');await Promise.all([loadSuggestions(),loadBrief(),loadAll()])}catch(e){toast(e.message)}};
 async function loadRisks(){const d=await get('risks');byId('assistantRisks').innerHTML=d.items.length?d.items.map(x=>card(x.title,x.detail,tag(x.level==='high'?'فوری':x.level==='medium'?'مهم':'توجه',x.level))).join(''):emptyText('موضوع پرخطری شناسایی نشده است')}
 async function askMemory(){const q=byId('memoryQuery').value.trim();if(q.length<2)return toast('حداقل دو حرف بنویس');try{const d=await get('memory?q='+encodeURIComponent(q));byId('memoryResults').innerHTML=`<div class="assistant-card"><h3>${safe(d.answer)}</h3></div>`+(d.sources.length?d.sources.map(x=>`<article class="assistant-card assistant-source"><h3>${safe(x.title)}</h3><p>${safe(x.detail||'')}</p><div class="assistant-meta">${tag(x.kind)}${tag(fmt(x.at))}</div></article>`).join(''):emptyText('منبع معتبری پیدا نشد'))}catch(e){toast(e.message)}}
 async function loadCommitments(){const d=await get('commitments');byId('assistantCommitments').innerHTML=d.items.length?d.items.map(x=>card(x.title,x.details,[tag(x.direction==='mine'?'قول من':'قول دیگران'),tag(x.status==='waiting'?'منتظر':'باز'),x.due_at?tag('موعد '+fmt(x.due_at)):'' ].join(''),`<button class="accept" onclick="finishCommitment('${x.id}')">انجام شد</button>`)).join(''):emptyText('تعهد بازی وجود ندارد')}
 window.finishCommitment=async id=>{try{await send('commitments/'+id,{status:'done'},'PATCH');toast('تعهد بسته شد');await Promise.all([loadCommitments(),loadBrief()])}catch(e){toast(e.message)}};
 async function loadDecisions(){const d=await get('decisions');byId('assistantDecisions').innerHTML=d.items.length?d.items.map(x=>card(x.title,x.decision,[x.reason?tag('دلیل ثبت شده'):'',x.review_at?tag('بازبینی '+fmt(x.review_at)):''].join(''))).join(''):emptyText('تصمیمی ثبت نشده است')}
 async function loadCalendar(){const d=await get('calendar');byId('assistantCalendar').innerHTML=d.items.length?d.items.map(x=>card(x.title,x.details,tag(fmt(x.starts_at)))).join(''):emptyText('رویدادی در بازه آینده ثبت نشده است')}
 async function loadPeople(){const d=await get('people');byId('assistantPeople').innerHTML=d.items.length?d.items.map(x=>card(x.name,x.notes,[tag(fa(x.facts)+' Fact'),tag(fa(x.documents)+' سند'),tag(fa(x.open_commitments)+' تعهد باز')].join(''))).join(''):emptyText('هنوز شخصی ثبت نشده است')}
 async function loadTimeline(){const d=await get('timeline?limit=150');byId('assistantTimeline').innerHTML=d.items.length?d.items.map(x=>card(x.title,x.detail,[tag(x.kind),tag(fmt(x.created_at))].join(''))).join(''):emptyText('خط زمانی خالی است')}
 async function loadReviews(){for(const kind of ['morning','evening']){const d=await get('reviews/'+kind);const value=d.item.content?.text||'';byId(kind+'Review').value=value}}

 const loaders={brief:loadBrief,suggestions:loadSuggestions,risks:loadRisks,memory:async()=>{},commitments:loadCommitments,decisions:loadDecisions,calendar:loadCalendar,people:loadPeople,timeline:loadTimeline,review:loadReviews};
 async function selectPanel(name){document.querySelectorAll('.assistant-panel').forEach(x=>x.classList.toggle('active',x.id==='assistant-'+name));document.querySelectorAll('.assistant-tab').forEach(x=>x.classList.toggle('active',x.dataset.panel===name));try{await loaders[name]()}catch(e){toast(e.message)}}
 window.openAssistantPanel=name=>{openSheet('assistantSheet');selectPanel(name)};
 document.querySelectorAll('.assistant-tab').forEach(x=>x.onclick=()=>selectPanel(x.dataset.panel));
 byId('assistantOpen')?.addEventListener('click',()=>{openSheet('assistantSheet');selectPanel('brief')});byId('assistantClose').onclick=()=>closeSheet('assistantSheet');
 byId('memoryAsk').onclick=askMemory;byId('memoryQuery').onkeydown=e=>{if(e.key==='Enter')askMemory()};
 byId('newCommitment').onclick=async()=>{const title=prompt('عنوان تعهد یا موضوع منتظر چیست؟');if(!title)return;const theirs=confirm('این قول یا اقدام بر عهده شخص دیگری است؟');try{await send('commitments',{title,direction:theirs?'theirs':'mine',status:theirs?'waiting':'open'});toast('تعهد ثبت شد');loadCommitments()}catch(e){toast(e.message)}};
 byId('newDecision').onclick=async()=>{const title=prompt('عنوان تصمیم چیست؟');if(!title)return;const decision=prompt('تصمیم نهایی را بنویس:');if(!decision)return;const reason=prompt('دلیل تصمیم چیست؟')||'';try{await send('decisions',{title,decision,reason});toast('تصمیم ثبت شد');loadDecisions()}catch(e){toast(e.message)}};
 byId('newEvent').onclick=async()=>{const title=prompt('عنوان رویداد یا موعد چیست؟');if(!title)return;const starts=prompt('زمان به شکل 2026-10-01T09:00:00+03:30');if(!starts)return;try{await send('calendar',{title,starts_at:starts});toast('رویداد ثبت شد');loadCalendar()}catch(e){toast(e.message)}};
 byId('calendarConfig').onclick=async()=>{try{const current=await get('calendar/config');const url=prompt('لینک خصوصی ICS تقویم Google یا Apple را وارد کن:',current.url||'');if(url===null)return;await send('calendar/config',{url});toast(url?'لینک تقویم ذخیره شد':'اتصال تقویم حذف شد')}catch(e){toast(e.message)}};
 byId('syncCalendar').onclick=async()=>{try{const d=await send('calendar/sync',{});toast(`${d.imported} رویداد جدید همگام شد`);loadCalendar()}catch(e){toast(e.message)}};
 document.querySelectorAll('[data-review]').forEach(button=>button.onclick=async()=>{const kind=button.dataset.review;try{await send('reviews/'+kind,{content:{text:byId(kind+'Review').value}});toast('مرور روز ذخیره شد')}catch(e){toast(e.message)}});

 // Add retained audio and explicit transcription control to voice Captures.
 if(window.captureHTML){const original=window.captureHTML;window.captureHTML=x=>{let html=original(x),vid=x.suggested_data?.voice_id;if(!vid)return html;const controls=`<div class="assistant-buttons"><audio controls style="width:100%" src="/api/personal/voice/${encodeURIComponent(vid)}"></audio><button class="accept" onclick="transcribePersonalVoice('${vid}')">تبدیل صوت به متن</button></div>`;return html.replace('</article>',controls+'</article>')}}
 window.transcribePersonalVoice=async vid=>{try{toast('تبدیل صوت شروع شد؛ ممکن است چند دقیقه طول بکشد');const d=await send('voice/'+vid+'/transcribe',{});toast('متن صوت به Capture تبدیل شد');await loadAll();go('inbox')}catch(e){toast(e.message)}};
})();
